sudo: required
  
services:
  - docker

language: scala

scala:
  - 2.11.8

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run -d --net=host --name mongo mongo:3.2
script:
  - ./sbt clean compile docker:publishLocal
  - docker run -d -p 9000:9000 --net=host sdkman/sdkman-hooks:1.1.7
  - ./sbt test

after_success:
  - sbt docker:publish

# blacklist
branches:
  except:
    - RELEASE
notifications:
  slack: sdkman:QdA1XVUuYDjlYL4Z7gm16OEc
